sonar.organization=furo347
sonar.projectKey=Furo347_CineLink
sonar.projectName=CineLink

sonar.sources=cinelink-backend/src,cinelink-frontend/src
sonar.tests=cinelink-backend/tests,cinelink-frontend/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts,**/*.config.js,cinelink-frontend/public/**
sonar.test.inclusions=cinelink-backend/tests/**/*.test.ts,cinelink-frontend/test/**/*.test.ts,cinelink-frontend/test/**/*.test.tsx
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/test/**,**/tests/**,cinelink-backend/src/server.ts,cinelink-backend/src/scripts/**

sonar.javascript.lcov.reportPaths=cinelink-backend/coverage/lcov.info,cinelink-frontend/coverage/lcov.info
sonar.typescript.tsconfigPaths=cinelink-backend/tsconfig.json,cinelink-frontend/tsconfig.app.json
